owner: crisvzq
repo: iptv-monitor

sites:
  # AMERICA IPTV
  - name: "[AMERICA] Panel"
    url: http://icomplay.net/ICOMPLAY/login
  - name: "[AMERICA] DNS 1"
    url: http://icomplay.net
    port: 80
  - name: "[AMERICA] DNS 2"
    url: http://iptvglobal.site
    port: 25461
  - name: "[AMERICA] DNS 3"
    url: http://latinostream.xyz
    port: 80

  # LATINO IPTV (Usando TCP para evitar bloqueos)
  - name: "[LATINO] Panel"
    url: https://mv-play.uk:8443/Reseller/login
  - name: "[LATINO] DNS 1"
    url: starlessro.uk
    port: 2082
    check: "tcp-ping"
  - name: "[LATINO] DNS 2"
    url: net01sys.uk
    port: 2082
    check: "tcp-ping"
  - name: "[LATINO] DNS 3"
    url: corex01.uk
    port: 2095
    check: "tcp-ping"

status-website:
  baseUrl: /iptv-monitor/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Estado BELION IPTV"
  introTitle: "Monitoreo de Estabilidad IPTV"
  introMessage: "Comparativa en tiempo real entre servidores AMERICA y LATINO."
  navbar:
    - title: Estado
      href: /iptv-monitor/
    - title: GitHub
      href: https://github.com/crisvzq/iptv-monitor

assignees:
  - crisvzq
